name: Rust CI

on:
  push:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
          rustup component add rustfmt --toolchain nightly

      - name: Lint
        run: |
          cargo +nightly fmt -- --check
          cargo clippy -- -D warnings

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: |
          cargo test --all
